docs(readme): add --save-dev
zendeskgarden/eslint-config pull request #186
Opened 2022-01-19 19:02 UTC by JamesSingleton

## Description

Just updates the readme to install the deps as dev dependencies

2022-01-19 19:33 UTC, mtomcal approved these changes

2022-01-19 20:46 UTC, jzempel requested changes
To be fair, as a matter of consistency, it was determined from the outset to refrain from specifying install flags – throughout all Garden READMEs – and leave that as a detail for the implementer. Notice, this same logic also applies to refraining from `npm` vs `yarn`, etc.

2022-01-19 21:28 UTC, mtomcal commented
How often do developers install `eslint-config` libraries to `dependencies` rather than `devDependencies` in practice? After running a [search of our own repos](https://github.com/search?l=JSON&p=1&q=org%3Azendeskgarden+eslint-config&type=Code) we only install this library to `devDependencies`. Shouldn't we advocate best practice here by signaling this is a developer dependency as a best practice? 

Also, aren't we signaling implicitly an opinion that this library should be installed to `dependencies`. If we examine `npm install <library>` [[1]](https://docs.npmjs.com/cli/v8/commands/npm-install) which is the same behavior as `npm install -S <library>` [[2]](https://docs.npmjs.com/cli/v8/commands/npm-install#save), we implicitly instruct our users to install this to `dependencies`.

2022-01-20 17:28 UTC, mtomcal commented
Then this becomes a choice of philosophy:

> Do we take a more hands-off approach and leave best practices to the developer?

or

> Do we try to bake best practices into our documentation in order to educate?

It seems the hands-off approach is at work here.

2022-01-21 18:01 UTC, closed without merging