chore(rules): adds new rules missed in v31
zendeskgarden/eslint-config pull request #205
Opened 2023-02-01 18:12 UTC by geotrev

- [x] **BREAKING CHANGE?** 

## Description

Forgot a handful of rules from the last renovate update.

## Detail

- @typescript-eslint/key-spacing
- react/no-object-type-as-default-prop
- react/sort-default-props
- jsx-a11y/prefer-tag-over-role
- jsx-a11y/no-aria-hidden-on-focusable
- jsx-a11y/anchor-ambiguous-text

2023-02-01 18:29 UTC, Francois-Esquire approved these changes

2023-02-01 19:13 UTC, jzempel requested changes

2023-02-01 19:13 UTC, jzempel commented on plugins/typescript-semantics.js
> +    'key-spacing': 0,
[nit] please keep this alphabetically sorted

2023-02-01 19:13 UTC, jzempel commented on plugins/react.js
> +    'jsx-a11y/prefer-tag-over-role': 0,
This rule is important to Garden and should be set to `2` error due to the [first rule of ARIA](https://www.w3.org/TR/using-aria/#rule1)

2023-02-01 19:13 UTC, jzempel commented on plugins/react.js
> +    'react/sort-default-props': 0,
[nit] please cut/past to retain alphabetical sorting

2023-02-01 19:13 UTC, jzempel commented on plugins/typescript-semantics.js
> +    }],
```suggestion
    '@typescript-eslint/key-spacing': stylisticIssues['key-spacing'],
```

with `stylisticIssues` require'd at top of file.

2023-02-01 20:20 UTC, geotrev commented
Fixed all the things: Fixed: 27a2f72b0485797f05b2be5ae24659403f7196c0

2023-02-01 20:53 UTC, jzempel approved these changes

2023-02-02 18:20 UTC, geotrev commented
Thanks for updating the title.

I also opened a bug against `jsx-a11y` about some HTML patterns that are likely false-errors (`prefer-tag-over-role`): https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/920

2023-02-02 18:20 UTC, merged